# The name that will appear for mail received from the console
console-name: Admin

gui:
  # Gui Format
  # - M: Mail Slot
  # - #: Border
  format:
    - "MMMMMMMMM"
    - "MMMMMMMMM"
    - "MMMMMMMMM"
    - "MMMMMMMMM"
    - "MMMMMMMMM"
    - "#########"
  items:
    text-mail:
      material: WRITABLE_BOOK
      display-name: "&f%title%"
    preview-mail:
      lore:
        - " "
        - "&#ffde8aʟᴇғᴛ ᴄʟɪᴄᴋ &7- Open mail"
        - "&#ffde8aʀɪɢʜᴛ ᴄʟɪᴄᴋ &7- Preview mail"
        - " "
        - "&8Mail ID: %mail_id%"
    border:
      material: WHITE_STAINED_GLASS_PANE
      display-name: "&7"

messages:
  no-permissions: "&cYou don't have permissions for this command"
  invalid-args: "&cInvalid arguments try: %command%"
  invalid-player: "&cCould not find player '%player%'"
  sent-mail: "&aSent mail to %receiver%"
  failed-to-send-mail: "&cSomething went wrong whilst trying to send mail"
  received-mail: "&aYou have received new mail from %sender%!"
  received-offline-mail: "&aYou have %count% new mail"
  deleted-mail: "&aRemoved mail '%mail_id%' from your mail list!"
  deleted-all-mail: "&aYour mail list has been cleared!"
  mail-not-found: "&cCould not find this mail in your mail list"
  no-mail: "&cCould not find any mail in your mail list"
  ignored: "&cYou cannot send mail to %player%"
  ignore-player: "&aYou will no longer receive mail from %player%"
  unignore-player: "&aYou can now receive mail from %player%"
  already-ignoring: "&cYou are already ignoring %player%"
  not-ignoring: "&cYou are not currently ignoring %player%"