name: LushMail
version: '${version}'
main: org.lushplugins.lushmail.LushMail
api-version: '1.20'
softdepend:
  - LuckPerms
commands:
  mail:
    usage: /mail
permissions:
  lushmail.open:
    default: true
  lushmail.preview:
    default: true